global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'kafkastreams-spring-cloud-stream-expl'
    metrics_path: '/cartorgon/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['10.68.8.95:8080']
      labels:
        name: kafkastreams-spring-cloud-stream-expl
        description: 'Demo Project for Spring Cloud Stream with Apache Kafka Streams'
        type: 'Spring Cloud Stream micro-service'
        version: 0.0.1-SNAPSHOT